"""Initial migration

Revision ID: 1abeb8405bd4
Revises: 
Create Date: 2025-08-25 12:02:10.104715+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abeb8405bd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyte_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('analyte_id', sa.Integer(), nullable=False),
    sa.Column('lab_name', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyte_mappings_analyte_id'), 'analyte_mappings', ['analyte_id'], unique=False)
    op.create_index(op.f('ix_analyte_mappings_id'), 'analyte_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_analyte_mappings_source_label'), 'analyte_mappings', ['source_label'], unique=False)
    op.create_table('analytes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('loinc_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_unit', sa.String(), nullable=True),
    sa.Column('unit_category', sa.String(), nullable=True),
    sa.Column('reference_ranges', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytes_code'), 'analytes', ['code'], unique=True)
    op.create_index(op.f('ix_analytes_id'), 'analytes', ['id'], unique=False)
    op.create_index(op.f('ix_analytes_loinc_code'), 'analytes', ['loinc_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('lab_name', sa.String(), nullable=True),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_extracted_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('analyte_id', sa.Integer(), nullable=True),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('raw_value', sa.String(), nullable=False),
    sa.Column('raw_unit', sa.String(), nullable=True),
    sa.Column('raw_reference_range', sa.String(), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('normalized_unit', sa.String(), nullable=True),
    sa.Column('normalized_reference_min', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('normalized_reference_max', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('is_numeric', sa.Boolean(), nullable=True),
    sa.Column('is_out_of_range', sa.Boolean(), nullable=True),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('is_suspect', sa.Boolean(), nullable=True),
    sa.Column('normalized', sa.Boolean(), nullable=True),
    sa.Column('previous_result_id', sa.Integer(), nullable=True),
    sa.Column('delta_value', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('delta_percent', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('lab_comments', sa.Text(), nullable=True),
    sa.Column('processing_notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analyte_id'], ['analytes.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['previous_result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_analytes_loinc_code'), table_name='analytes')
    op.drop_index(op.f('ix_analytes_id'), table_name='analytes')
    op.drop_index(op.f('ix_analytes_code'), table_name='analytes')
    op.drop_table('analytes')
    op.drop_index(op.f('ix_analyte_mappings_source_label'), table_name='analyte_mappings')
    op.drop_index(op.f('ix_analyte_mappings_id'), table_name='analyte_mappings')
    op.drop_index(op.f('ix_analyte_mappings_analyte_id'), table_name='analyte_mappings')
    op.drop_table('analyte_mappings')
    # ### end Alembic commands ###